-- NO-OP MIGRATION (placeholder)
-- This legacy migration originally removed auth-related tables/columns.
-- It is intentionally empty so it can safely run as the first migration
-- in a fresh SQLite database without failing on missing tables.
